### ISSUE TITLE
Drop flask-apispec support

### ISSUE THREAD

**Issue by aprilahijriyan** [zemfrog/zemfrog#63]
I am now planning to drop flask-apispec support. Because there are issues with the extension, including:

* https://github.com/jmcarp/flask-apispec/issues/122

I've found a flask-apispec replacement extension which is [FlaskEase](https://github.com/zero-shubham/flask-ease)
And I plan to use it. But, I'm also open to other suggestions.

**Comment by lafrech** [comment]
I don't know FlaskEase. You could be interested in [flask-smorest](https://github.com/marshmallow-code/flask-smorest).

flask-smorest uses marshmallow. FlaskEase uses pydantic.

**Comment by aprilahijriyan** [comment]
Interesting, I'll try later. thanks

**Comment by aprilahijriyan** [comment]
Hi @lafrech, Does flask-smorest have a configuration to not enable swagger-ui? (for example, when the application is in our production environment not using swagger-ui)

**Comment by lafrech** [comment]
Sure. It is off by default.

https://flask-smorest.readthedocs.io/en/latest/openapi.html#serve-the-openapi-documentation

More precisely, the docs is always generated, but serving it is optional and opt-in.

I forgot to mention that I wrote it because I was not satisfied with flask-apispec but it looks very much like it so the move shouldn't be too hard.

**Comment by aprilahijriyan** [comment]
Yes, I feel the same way too.

**Comment by aprilahijriyan** [comment]
Is adding a security schema the same as flask-apispec?

**Comment by aprilahijriyan** [comment]
> Is adding a security schema the same as flask-apispec?

@lafrech ?

**Comment by lafrech** [comment]
Can't help you. Don't know flask-apispec.

**Comment by aprilahijriyan** [comment]
Hi @lafrech, can `flask-smorest` create a path to `swagger-ui` without a `blueprint`?
